### ISSUE TITLE
How to reset scaling to the original?

### ISSUE THREAD

**Issue by OstapenkoYevgeniy** [martinwithaar/PinchToZoom#14]
Hi! Thanks for the great library.

There is one problem.
1) I do imgViev.setImageBitmap(bitmap)
2) Enlarge the image, but do not reduce it.
3) Upload the next image in imgView
4) It is immediately on an enlarged scale, and I want it to be in the original. How to finish this? 

Thank you!

P.S. I found a solution!

```
        try {
            imageMatrixTouchHandler.animateZoom(0, 0);
        } catch (Exception ignore) {
        }
```
try/catch need, because there may be an exception

W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Matrix.getValues(float[])' on a null object reference
        at com.bogdwellers.pinchtozoom.MatrixCorrector.getValues(MatrixCorrector.java:96)

**Comment by martinwithaar** [comment]
See if the answer in #6 works for you and please post back.

**Comment by OstapenkoYevgeniy** [comment]
> See if the answer in #6 works for you and please post back.

Answer # 6 did not work for me, after the reset, I had indents on the left and above

**Comment by DilumD** [comment]
> Hi! Thanks for the great library.
> 
> There is one problem.
> 
> 1. I do imgViev.setImageBitmap(bitmap)
> 2. Enlarge the image, but do not reduce it.
> 3. Upload the next image in imgView
> 4. It is immediately on an enlarged scale, and I want it to be in the original. How to finish this?
> 
> Thank you!
> 
> P.S. I found a solution!
> 
> ```
>         try {
>             imageMatrixTouchHandler.animateZoom(0, 0);
>         } catch (Exception ignore) {
>         }
> ```
> try/catch need, because there may be an exception
> 
> W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Matrix.getValues(float[])' on a null object reference
> at com.bogdwellers.pinchtozoom.MatrixCorrector.getValues(MatrixCorrector.java:96)

where to put this code if using setOnTouchListener

**Comment by ndubbaka** [comment]
@DilumD 
```
 imageMatrixTouchHandler = new ImageMatrixTouchHandler(mContext, corrector) {
            @Override
            public boolean onTouch(View view, final MotionEvent event) {
                        super.onTouch(view, event);
            }
};
TouchImageView.super.setOnTouchListener(imageMatrixTouchHandler);

        try {
            imageMatrixTouchHandler.animateZoom(0, 0);
        } catch (Exception e) {
            e.printStackTrace();
        }
```
